services:
  FizzBuzz\App\FizzBuzzSequencePrinter:
    public: true
    arguments:
      $fizzBuzz: '@FizzBuzz\Core\NumberConverter'
      $output: '@FizzBuzz\App\OutputInterface'

  FizzBuzz\Core\NumberConverter:
    $rules:
      - '@fizzbuzz.rule.fizz'
      - '@fizzbuzz.rule.buzz'
      - '@FizzBuzz\Spec\PassThroughRule'

  fizzbuzz.rule.fizz:
    class: FizzBuzz\Spec\CyclicNumberRule
    arguments: [3, 'Fizz']

  fizzbuzz.rule.buzz:
    class: FizzBuzz\Spec\CyclicNumberRule
    arguments: [5, 'Buzz']

  FizzBuzz\Spec\PassThroughRule: ~

  FizzBuzz\App\OutputInterface:
    class: FizzBuzz\ConsoleOutput
